spring:
  application:
    name: chemi-log

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:chemi_log}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER:chemilog}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
